apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: table-order
  labels:
    app: admin-service
    app.kubernetes.io/name: admin-service
    app.kubernetes.io/part-of: table-order
spec:
  type: ClusterIP
  selector:
    app: admin-service
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
