apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: table-order-cluster
  region: us-east-1
  version: "1.28"

iam:
  withOIDC: true

managedNodeGroups:
  - name: app-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 5
    volumeSize: 30
    labels:
      role: app
    tags:
      Environment: prod
      Project: table-order

cloudWatch:
  clusterLogging:
    enableTypes:
      - api
      - audit
      - authenticator
      - controllerManager
      - scheduler
